services:
  catalogue:
    build:
      context: ./catalogue
      dockerfile: Dockerfile
    image: dpavan/catalogue:2.0.0
    container_name: catalogue
    depends_on:
    - mongodb
  
  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    image: dpavan/user:2.0.0
    container_name: user
    depends_on:
    - redis

  cart:
    build:
      context: ./cart
      dockerfile: Dockerfile
    image: dpavan/cart:2.0.0
    container_name: cart
    depends_on:
    - catalogue
    - redis


  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: dpavan/frontend:2.0.0
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping

  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile  # it moves to mongodb dir
    image: dpavan/mongodb:2.0.0  # it is equal to docker build -t dpavan/mongodb:2.0.0
    container_name: mongodb

  redis:
    image: redis:7.0
    container_name: redis
  
  mysql:
    build: 
      context: ./mysql
      dockerfile: Dockerfile
    image: dpavan/mysql:2.0.0
    container_name: mysql

networks:
  default:
    driver: bridge
    name: roboshop
    external: false #it will create network manually