services:
  catalogue:
    build: ./catalogue
    image: dpavan/catalogue:2.0.0
    container_name: catalogue
    depends_on:
    - mongodb
  
  user:
    build: ./user
    image: dpavan/user:2.0.0
    container_name: user
    depends_on:
    - redis

  cart:
    build: ./cart
    image: dpavan/cart:2.0.0
    container_name: cart
    depends_on:
    - catalogue
    - redis

  shipping:
    build: ./shipping
    image: dpavan/shipping:2.0.0
    container_name: shipping
    depends_on:
    - mysql
    - cart
  
  payment:
    build: ./payment
    image: joindevops/payment:1.0.0
    container_name: payment
    environment:
      CART_HOST: "cart"
      CART_PORT: "8080"
      USER_HOST: "user"
      USER_PORT: "8080"
      AMQP_HOST: "rabbitmq"
      AMQP_USER: "roboshop"
      AMQP_PASS: "roboshop123"
    depends_on:
    - rabbitmq
    - cart
    - user
  
  frontend:
    build: ./frontend
    image: dpavan/frontend:2.0.0
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment

  mongodb:
    build: ./mongodb
     # it moves to mongodb dir
    image: dpavan/mongodb:2.0.0  # it is equal to docker build -t dpavan/mongodb:2.0.0
    container_name: mongodb

  redis:
    image: redis:7.0
    container_name: redis
  
  mysql:
    build: ./mysql
    image: dpavan/mysql:2.0.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: RoboShop@1

  rabbitmq:
    image: rabbitmq:3
    environment:
      RABBITMQ_DEFAULT_PASS: roboshop123
      RABBITMQ_DEFAULT_USER: roboshop
    container_name: rabbitmq

networks:
  default:
    driver: bridge
    name: roboshop
    external: false #it will create network manually